export const GET_CONCERTS = 'GET_CONCERTS';
export const ADD_CONCERT = 'ADD_CONCERT';
export const GET_CONCERT = 'GET_CONCERT';
export const UPDATE_CONCERT = 'UPDATE_CONCERT';
export const DELETE_CONCERT = 'DELETE_CONCERT';
export const SET_LOADING = 'SET_LOADING';
export const CONCERTS_ERROR = 'CONCERTS_ERROR';
